eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:${EUREKA_PORT:8761}/eureka/}
    register-with-eureka: true
ribbon:
  ReadTimeout: 60000

token: 
  key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
  expiration: 10

spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongoadmin
      password: fl200110
      database: minion_project_db
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
    