eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
ribbon:
  ReadTimeout: 60000

token: 
  key: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
  expiration: 10

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: aws
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql:${DB_URI://localhost:5432}/minion_project_db
    username: ${PSQLUSER:postgres}
    password: ${PSQLPASS:fl200110}
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

app:
  subscription:
    plans:
      -
        key: BASIC
        name: Plan inicial
        maxPlaces: 5
        maxPlaceImages: 10
        price: 100
      -
        key: BASIC_YEAR
        name: Plan inicial (anual)
        maxPlaces: 5
        maxPlaceImages: 10
        price: 1000
      -
        key: ADVANCE20
        name: Plan avanzado
        maxPlaces: 20
        maxPlaceImages: 15
        price: 300
      -
        key: ADVANCE20_YEAR
        name: Plan avanzado (anual)
        maxPlaces: 20
        maxPlaceImages: 15
        price: 3000
      -
        key: ULTIMATE0
        name: Plan ultimate
        maxPlaces: 80
        maxplaceImages: 30
        price: 500
      -
        key: ULTIMATE0_YEAR
        name: Plan ultimate (anual)
        maxPlaces: 80
        maxplaceImages: 30
        price: 5000
      -
        key: INTERN
        name: Interno
        maxPlaces: 0
        maxPlaceImages: 0
        monthlyFee: 0
        yearlyFee: 0

menu:
  main:
    options:
      -
        label: Inicio
        icon: home
        order: 1
        any: true
        route: /
      -
        label: Lugares
        icon: apartment
        order: 5
        any: true
        route: /op/places
      -
        label: Rentas
        icon: edit_calendar
        order: 10
        any: true
        route: /op/rents
      -
        label: Calendario
        icon: event
        order: 15
        any: true
        route: /op/calendar
      -
        label: Crear usuario
        icon: person_add
        order: 20
        any: false
        route: /users/create
        roles:
          - ROLE_ADMIN
          - ROLE_USERS_MANAGER
          - ROLE_WRITE_USERS
      -
        label: Administrar usuarios
        icon: people
        order: 20
        any: false
        route: /users/manage
        roles:
          - ROLE_ADMIN
          - ROLE_USERS_MANAGER

  places:
    options:
      -
        title: Reservar
        subtitle: Agenda una reservacion.
        icon: event
        order: 1
        any: true
        action: book
      -
        title: Bloquear fecha
        subtitle: Marcar fechas como no disponible para renta.
        icon: event_busy
        order: 3
        any: false
        action: block
        roles:
          - ROLE_PLACES_MANAGER
      -
        title: Enviar perfil
        subtitle: Envia la pagina de perfil del lugar.
        icon: send
        order: 5
        any: true
        action: profile
      -
        title: Enviar cuenta bancaria
        subtitle: Envia la cuenta bancaria la interesado.
        icon: account_balance
        order: 7
        any: true
        action: bank_account
      -
        title: Compartir
        subtitle: Comparte tu lugar para que alguien mas pueda agendar.
        icon: share
        order: 9
        any: false
        action: share
        roles:
          - ROLE_SHARE_PLACES
          - ROLE_PLACES_MANAGER
      -
        title: Configuración
        subtitle: Configura precios, monto de deposito y anticipo, imgágenes.
        icon: settings
        order: 11
        any: false
        action: config
        roles:
          - ROLE_WRITE_PLACES
          - ROLE_PLACES_MANAGER
          - ROLE_ADMIN
      -
        title: Precio extra
        subtitle: Configura el aumento de precio por noche para el alojamiento.
        icon: currency_exchange
        order: 12
        any: false
        action: extraPrice
        roles:
          - ROLE_CAN_EXTRA_PRICE
      -
        title: Modificar
        subtitle: Habilita para modificar el lugar.
        icon: edit
        order: 13
        any: false
        action: edit
        roles:
          - ROLE_WRITE_PLACES
          - ROLE_PLACES_MANAGER
          - ROLE_ADMIN
      -
        title: Eliminar
        subtitle: Borrar el lugar, ya no sera visible.
        icon: delete
        order: 15
        any: true
        action: delete

storage:
  aws:
    access:
      id: ${AWS_ID:none}
      secret: ${AWS_SECRET:none}
      region: us-west-1
    bucket: ziaric-minion-project
  local:
      base: /home/ubuntu/minion_local_storage

    